name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run (skip git push and publish)'
        required: true
        type: boolean
        default: false
      releaseType:
        description: 'Release Type'
        required: true
        type: choice
        default: 'stable'
        options:
          - stable
          - beta
          - alpha
          - patch
          - minor
          - major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push commits and tags
      issues: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Run Release (Dry Run)
        if: ${{ inputs.dryRun }}
        run: |
          case "${{ inputs.releaseType }}" in
            stable)
              bun nx release --dry-run --yes
              ;;
            beta|alpha)
              bun nx release prerelease --preid=${{ inputs.releaseType }} --dry-run --yes
              ;;
            patch|minor|major)
              bun nx release ${{ inputs.releaseType }} --dry-run --yes
              ;;
          esac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Release
        if: ${{ !inputs.dryRun }}
        run: |
          case "${{ inputs.releaseType }}" in
            stable)
              bun nx release --yes
              ;;
            beta|alpha)
              bun nx release prerelease --preid=${{ inputs.releaseType }} --yes
              ;;
            patch|minor|major)
              bun nx release ${{ inputs.releaseType }} --yes
              ;;
          esac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
